package cgl.iotcloud.samples.arducopter.client;

import javax.swing.*;

public class CopterUIGen extends javax.swing.JPanel {

    /**
     * Creates new form CopterUI
     */
    public CopterUIGen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        thrustpb = new javax.swing.JSlider();
        yawpb = new javax.swing.JSlider();
        rollpb = new javax.swing.JSlider();
        pitchpb = new javax.swing.JSlider();
        pitchlb = new javax.swing.JLabel();
        thrustlb1 = new javax.swing.JLabel();
        yawlb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        resetBttn = new javax.swing.JButton();
        enableBttn = new javax.swing.JToggleButton();
        hudPanel = new javax.swing.JPanel();
        jsCheckBox = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(700, 800));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null}
                },
                new String [] {
                        "Title 1", "Title 2"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        thrustpb.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        thrustpb.setOrientation(javax.swing.JSlider.VERTICAL);

        yawpb.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N

        rollpb.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N

        pitchpb.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        pitchpb.setOrientation(javax.swing.JSlider.VERTICAL);

        pitchlb.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        pitchlb.setText("Pitch");

        thrustlb1.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        thrustlb1.setText("Thrust");

        yawlb.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        yawlb.setText("Yaw");

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        jLabel1.setText("Roll");

        resetBttn.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        resetBttn.setText("Reset");

        enableBttn.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        enableBttn.setText("Enable");

        hudPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout hudPanelLayout = new javax.swing.GroupLayout(hudPanel);
        hudPanel.setLayout(hudPanelLayout);
        hudPanelLayout.setHorizontalGroup(
                hudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        hudPanelLayout.setVerticalGroup(
                hudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        jsCheckBox.setText("Joystick");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(hudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(101, 101, 101)
                                                                .addComponent(thrustpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(thrustlb1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(pitchpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(pitchlb)
                                                                .addGap(42, 42, 42))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(yawpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                                                                .addComponent(rollpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(99, 99, 99)
                                                                .addComponent(yawlb)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel1)
                                                                .addGap(89, 89, 89))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(enableBttn)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(resetBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jsCheckBox)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                                        .addComponent(hudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(resetBttn)
                                        .addComponent(enableBttn)
                                        .addComponent(jsCheckBox))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(9, 9, 9)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(pitchpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(thrustpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(pitchlb)
                                                                                .addGap(88, 88, 88))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(thrustlb1)
                                                                                .addGap(89, 89, 89)))))
                                                .addGap(25, 25, 25)
                                                .addComponent(yawpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rollpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(yawlb))
                                .addContainerGap())
        );
    }// </editor-fold>
    // Variables declaration - do not modify
    protected javax.swing.JToggleButton enableBttn;
    protected javax.swing.JPanel hudPanel;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable jTable1;
    protected javax.swing.JCheckBox jsCheckBox;
    protected javax.swing.JLabel pitchlb;
    protected javax.swing.JSlider pitchpb;
    protected javax.swing.JButton resetBttn;
    protected javax.swing.JSlider rollpb;
    protected javax.swing.JLabel thrustlb1;
    protected javax.swing.JSlider thrustpb;
    protected javax.swing.JLabel yawlb;
    protected javax.swing.JSlider yawpb;
    // End of variables declaration
}
